In [11]:
import numpy as np

In [12]:
# Creating an array of evenly spaced values between start and end
arr12 = np.linspace(0, 1, 11)
print(arr12)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [3]:
# Creating an array of random integers between low and high
arr13 = np.random.randint(low=0, high=10, size=(3, 3))
print(arr13)

[[9 9 8]
 [4 4 2]
 [8 1 7]]


In [4]:
# Flattening a multi-dimensional array to a one-dimensional array
arr14 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr14_flat = arr14.flatten()
print(arr14_flat)

[1 2 3 4 5 6 7 8 9]


In [5]:
# Concatenating arrays horizontally
arr15 = np.array([1, 2, 3])
arr16 = np.array([4, 5, 6])
arr15_16_horizontal = np.hstack((arr15, arr16))
print(arr15_16_horizontal)

[1 2 3 4 5 6]


In [6]:
# Concatenating arrays vertically
arr17 = np.array([[1], [2], [3]])
arr18 = np.array([[4], [5], [6]])
arr17_18_vertical = np.vstack((arr17, arr18))
print(arr17_18_vertical)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [7]:
# Resizing an array
arr19 = np.array([1, 2, 3])
arr19_resize = np.resize(arr19, (5,))
print(arr19_resize)

[1 2 3 1 2]


In [8]:
# Sorting an array
arr20 = np.array([3, 2, 1, 5, 4])
arr20_sorted = np.sort(arr20)
print(arr20_sorted)

[1 2 3 4 5]


In [9]:
# Finding unique elements in an array
arr21 = np.array([1, 2, 2, 3, 3, 3, 4, 5, 5])
arr21_unique = np.unique(arr21)
print(arr21_unique)

[1 2 3 4 5]


In [10]:
# Finding the maximum and minimum values in an array
arr22 = np.array([1, 2, 3, 4, 5])
arr22_max = np.max(arr22)
arr22_min = np.min(arr22)
print(arr22_max)
print(arr22_min)

5
1
