In [2]:
import numpy as np

# Creating a one-dimensional NumPy array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]


In [3]:
# Creating a two-dimensional NumPy array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [4]:
# Creating an array of zeros
zeros = np.zeros((3, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
# Creating an array of ones
ones = np.ones((2, 4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:

# Creating a random array
rand = np.random.rand(2, 3)
print(rand)

[[0.00653316 0.29441653 0.47805732]
 [0.45236539 0.94569685 0.95220574]]


In [7]:
# Indexing and slicing arrays
print(arr1[0])
print(arr2[1, 2])
print(arr1[1:4])

1
6
[2 3 4]


In [8]:
# Reshaping arrays
arr3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr3_reshape = arr3.reshape((3, 3))
print(arr3_reshape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
# Mathematical operations on arrays
arr4 = np.array([1, 2, 3, 4, 5])
arr5 = np.array([6, 7, 8, 9, 10])
print(arr4 + arr5)
print(arr4 * arr5)
print(np.dot(arr4, arr5))

[ 7  9 11 13 15]
[ 6 14 24 36 50]
130


In [10]:
# Linear algebra operations
arr6 = np.array([[1, 2], [3, 4]])
arr7 = np.array([[5, 6], [7, 8]])
print(np.linalg.det(arr6))
print(np.linalg.inv(arr6))
print(np.dot(arr6, arr7))

-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]
[[19 22]
 [43 50]]


In [11]:

# Statistical operations on arrays
arr8 = np.array([1, 2, 3, 4, 5])
print(np.mean(arr8))
print(np.median(arr8))
print(np.std(arr8))
print(np.var(arr8))

3.0
3.0
1.4142135623730951
2.0


In [12]:
# numpy.arange() function
arr9 = np.arange(0, 10, 2)
print(arr9)

[0 2 4 6 8]


In [13]:
# numpy.eye() function
arr10 = np.eye(3)
print(arr10)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
# numpy.transpose() function
arr11 = np.array([[1, 2, 3], [4, 5, 6]])
arr11_transpose = np.transpose(arr11)
print(arr11_transpose)

[[1 4]
 [2 5]
 [3 6]]
